### ISSUE TITLE
Re-upload to MCBBS

### ISSUE THREAD

**Issue by ghost** [SalmonDE/GuessTheNumber#8]
Hi author!
The GuessTheNumber Plugin is great，could I reproduce the files to mcbbs? I marked you as the author in the MCBBS，Users download the files in your original github

**Comment by Aericio** [comment]
可以，因为我们用[GPLv3](https://jxself.org/translations/gpl-3.zh.shtml)许可。
请给我们MCBBS的链接 when you upload.
我的中文不是很好，所以下面有英文。

> Yes, as stated by GPLv3 license, you are allowed distribute the plugin as long as the original source is disclosed.
Also, please provide a link to the MCBBS page so we can check.

**Comment by Aericio** [comment]
MCBBS: https://www.mcbbs.net/thread-963648-1-1.html

**Comment by Aericio** [comment]
(deleted)
